# Generated by Django 2.2.7 on 2019-11-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单号')),
                ('kami', models.CharField(max_length=18, verbose_name='卡密')),
                ('order_name', models.CharField(max_length=18, verbose_name='商品名/套餐')),
                ('order_status', models.CharField(max_length=8, verbose_name='订单状态')),
                ('qr_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='实付金额')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_save', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('user_email', models.EmailField(max_length=254, verbose_name='买家邮箱')),
                ('user_ip', models.CharField(blank=True, max_length=36, null=True, verbose_name='买家IP')),
                ('qr_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='二维码')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'tb_order',
            },
        ),
        migrations.CreateModel(
            name='Taocan',
            fields=[
                ('taocan', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='套餐')),
                ('alipay_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='支付宝价格')),
                ('wechat_price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='微信价格')),
            ],
            options={
                'verbose_name': '套餐',
                'verbose_name_plural': '套餐',
                'db_table': 'tb_taocan',
            },
        ),
        migrations.CreateModel(
            name='Kami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kami', models.CharField(max_length=18, verbose_name='卡密')),
                ('use', models.BooleanField(default=0, verbose_name='是否锁定')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_save', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('taocan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chongzhi.Taocan')),
            ],
            options={
                'verbose_name': '卡密',
                'verbose_name_plural': '卡密',
                'db_table': 'tb_kami',
            },
        ),
    ]
