# Generated by Django 2.2.7 on 2019-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0002_auto_20191116_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(default='alipay', max_length=6, verbose_name='支付方式'),
            preserve_default=False,
        ),
    ]
