# Generated by Django 2.2.7 on 2019-11-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0003_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sessionid',
            field=models.CharField(default='wertyuhgvdfghdsdfghj', max_length=100, verbose_name='用户cookie'),
            preserve_default=False,
        ),
    ]
