# Generated by Django 2.2.7 on 2019-11-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0007_order_beizhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='APP_POST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=8, verbose_name='金额')),
                ('encrypt', models.CharField(max_length=2, verbose_name='是否加密')),
                ('time', models.CharField(max_length=20, verbose_name='时间')),
                ('type', models.CharField(max_length=8, verbose_name='支付方式')),
                ('deviceid', models.CharField(max_length=100, verbose_name='设备号')),
                ('content', models.CharField(max_length=100, verbose_name='详细内容')),
            ],
            options={
                'verbose_name': 'APP推送的收款信息',
                'verbose_name_plural': 'APP推送的收款信息',
                'db_table': 'tb_app_post',
            },
        ),
    ]
