# Generated by Django 2.2.7 on 2019-11-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0008_app_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_post',
            name='title',
            field=models.CharField(default='zhifubao', max_length=15, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
