# Generated by Django 2.2.7 on 2019-11-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0011_auto_20191125_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taocan',
            name='shangpin',
        ),
    ]
