# Generated by Django 2.2.7 on 2019-11-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0012_remove_taocan_shangpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taocan',
            name='shangpin',
            field=models.ForeignKey(default='无为WIFI卡密', on_delete=django.db.models.deletion.PROTECT, to='chongzhi.Shangpin'),
            preserve_default=False,
        ),
    ]
