# Generated by Django 2.2.7 on 2019-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0014_auto_20191125_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kami',
            name='kami',
            field=models.CharField(max_length=32, unique=True, verbose_name='卡密'),
        ),
    ]
