# Generated by Django 2.2.7 on 2019-12-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0015_auto_20191125_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_post',
            name='type',
            field=models.CharField(max_length=20, verbose_name='支付方式'),
        ),
    ]
