# Generated by Django 3.0.3 on 2020-06-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0016_auto_20191216_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='taocan',
            name='paypal_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='PayPal价格'),
            preserve_default=False,
        ),
    ]
