# Generated by Django 3.0.3 on 2020-11-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0017_taocan_paypal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kami',
            name='use',
            field=models.PositiveSmallIntegerField(default=0, max_length=1, verbose_name='卡密状态'),
        ),
    ]
