# Generated by Django 3.0.3 on 2020-11-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chongzhi', '0019_auto_20201108_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taocan',
            name='paypal_price',
        ),
    ]
