# Generated by Django 2.2.7 on 2019-11-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaxun', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
