# Generated by Django 2.2.7 on 2019-11-19 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaxun', '0002_auto_20191119_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
